// Geo data for the selector — comprehensive world coverage
export type GeoType = "country" | "county" | "state" | "province" | "region" | "continent";

export type GeoOption = {
  value: string;
  label: string;
  type: GeoType;
  parent?: string;
};

export const CONTINENTS: GeoOption[] = [
  { value: "africa", label: "Africa", type: "continent" },
  { value: "asia", label: "Asia", type: "continent" },
  { value: "europe", label: "Europe", type: "continent" },
  { value: "north-america", label: "North America", type: "continent" },
  { value: "south-america", label: "South America", type: "continent" },
  { value: "oceania", label: "Oceania", type: "continent" },
  { value: "middle-east", label: "Middle East", type: "continent" },
];

export const COUNTRIES: GeoOption[] = [
  // ── AFRICA ──
  { value: "DZ", label: "Algeria", type: "country", parent: "africa" },
  { value: "AO", label: "Angola", type: "country", parent: "africa" },
  { value: "BJ", label: "Benin", type: "country", parent: "africa" },
  { value: "BW", label: "Botswana", type: "country", parent: "africa" },
  { value: "BF", label: "Burkina Faso", type: "country", parent: "africa" },
  { value: "BI", label: "Burundi", type: "country", parent: "africa" },
  { value: "CV", label: "Cabo Verde", type: "country", parent: "africa" },
  { value: "CM", label: "Cameroon", type: "country", parent: "africa" },
  { value: "CF", label: "Central African Republic", type: "country", parent: "africa" },
  { value: "TD", label: "Chad", type: "country", parent: "africa" },
  { value: "KM", label: "Comoros", type: "country", parent: "africa" },
  { value: "CG", label: "Congo", type: "country", parent: "africa" },
  { value: "CD", label: "DR Congo", type: "country", parent: "africa" },
  { value: "CI", label: "Côte d'Ivoire", type: "country", parent: "africa" },
  { value: "DJ", label: "Djibouti", type: "country", parent: "africa" },
  { value: "EG", label: "Egypt", type: "country", parent: "africa" },
  { value: "GQ", label: "Equatorial Guinea", type: "country", parent: "africa" },
  { value: "ER", label: "Eritrea", type: "country", parent: "africa" },
  { value: "SZ", label: "Eswatini", type: "country", parent: "africa" },
  { value: "ET", label: "Ethiopia", type: "country", parent: "africa" },
  { value: "GA", label: "Gabon", type: "country", parent: "africa" },
  { value: "GM", label: "Gambia", type: "country", parent: "africa" },
  { value: "GH", label: "Ghana", type: "country", parent: "africa" },
  { value: "GN", label: "Guinea", type: "country", parent: "africa" },
  { value: "GW", label: "Guinea-Bissau", type: "country", parent: "africa" },
  { value: "KE", label: "Kenya", type: "country", parent: "africa" },
  { value: "LS", label: "Lesotho", type: "country", parent: "africa" },
  { value: "LR", label: "Liberia", type: "country", parent: "africa" },
  { value: "LY", label: "Libya", type: "country", parent: "africa" },
  { value: "MG", label: "Madagascar", type: "country", parent: "africa" },
  { value: "MW", label: "Malawi", type: "country", parent: "africa" },
  { value: "ML", label: "Mali", type: "country", parent: "africa" },
  { value: "MR", label: "Mauritania", type: "country", parent: "africa" },
  { value: "MU", label: "Mauritius", type: "country", parent: "africa" },
  { value: "MA", label: "Morocco", type: "country", parent: "africa" },
  { value: "MZ", label: "Mozambique", type: "country", parent: "africa" },
  { value: "NA", label: "Namibia", type: "country", parent: "africa" },
  { value: "NE", label: "Niger", type: "country", parent: "africa" },
  { value: "NG", label: "Nigeria", type: "country", parent: "africa" },
  { value: "RW", label: "Rwanda", type: "country", parent: "africa" },
  { value: "ST", label: "São Tomé and Príncipe", type: "country", parent: "africa" },
  { value: "SN", label: "Senegal", type: "country", parent: "africa" },
  { value: "SC", label: "Seychelles", type: "country", parent: "africa" },
  { value: "SL", label: "Sierra Leone", type: "country", parent: "africa" },
  { value: "SO", label: "Somalia", type: "country", parent: "africa" },
  { value: "ZA", label: "South Africa", type: "country", parent: "africa" },
  { value: "SS", label: "South Sudan", type: "country", parent: "africa" },
  { value: "SD", label: "Sudan", type: "country", parent: "africa" },
  { value: "TZ", label: "Tanzania", type: "country", parent: "africa" },
  { value: "TG", label: "Togo", type: "country", parent: "africa" },
  { value: "TN", label: "Tunisia", type: "country", parent: "africa" },
  { value: "UG", label: "Uganda", type: "country", parent: "africa" },
  { value: "ZM", label: "Zambia", type: "country", parent: "africa" },
  { value: "ZW", label: "Zimbabwe", type: "country", parent: "africa" },
  // ── ASIA ──
  { value: "AF", label: "Afghanistan", type: "country", parent: "asia" },
  { value: "BD", label: "Bangladesh", type: "country", parent: "asia" },
  { value: "BT", label: "Bhutan", type: "country", parent: "asia" },
  { value: "BN", label: "Brunei", type: "country", parent: "asia" },
  { value: "KH", label: "Cambodia", type: "country", parent: "asia" },
  { value: "CN", label: "China", type: "country", parent: "asia" },
  { value: "IN", label: "India", type: "country", parent: "asia" },
  { value: "ID", label: "Indonesia", type: "country", parent: "asia" },
  { value: "JP", label: "Japan", type: "country", parent: "asia" },
  { value: "KZ", label: "Kazakhstan", type: "country", parent: "asia" },
  { value: "KG", label: "Kyrgyzstan", type: "country", parent: "asia" },
  { value: "LA", label: "Laos", type: "country", parent: "asia" },
  { value: "MY", label: "Malaysia", type: "country", parent: "asia" },
  { value: "MV", label: "Maldives", type: "country", parent: "asia" },
  { value: "MN", label: "Mongolia", type: "country", parent: "asia" },
  { value: "MM", label: "Myanmar", type: "country", parent: "asia" },
  { value: "NP", label: "Nepal", type: "country", parent: "asia" },
  { value: "KP", label: "North Korea", type: "country", parent: "asia" },
  { value: "PK", label: "Pakistan", type: "country", parent: "asia" },
  { value: "PH", label: "Philippines", type: "country", parent: "asia" },
  { value: "SG", label: "Singapore", type: "country", parent: "asia" },
  { value: "KR", label: "South Korea", type: "country", parent: "asia" },
  { value: "LK", label: "Sri Lanka", type: "country", parent: "asia" },
  { value: "TW", label: "Taiwan", type: "country", parent: "asia" },
  { value: "TJ", label: "Tajikistan", type: "country", parent: "asia" },
  { value: "TH", label: "Thailand", type: "country", parent: "asia" },
  { value: "TL", label: "Timor-Leste", type: "country", parent: "asia" },
  { value: "TM", label: "Turkmenistan", type: "country", parent: "asia" },
  { value: "UZ", label: "Uzbekistan", type: "country", parent: "asia" },
  { value: "VN", label: "Vietnam", type: "country", parent: "asia" },
  // ── EUROPE ──
  { value: "AL", label: "Albania", type: "country", parent: "europe" },
  { value: "AD", label: "Andorra", type: "country", parent: "europe" },
  { value: "AT", label: "Austria", type: "country", parent: "europe" },
  { value: "BY", label: "Belarus", type: "country", parent: "europe" },
  { value: "BE", label: "Belgium", type: "country", parent: "europe" },
  { value: "BA", label: "Bosnia and Herzegovina", type: "country", parent: "europe" },
  { value: "BG", label: "Bulgaria", type: "country", parent: "europe" },
  { value: "HR", label: "Croatia", type: "country", parent: "europe" },
  { value: "CY", label: "Cyprus", type: "country", parent: "europe" },
  { value: "CZ", label: "Czech Republic", type: "country", parent: "europe" },
  { value: "DK", label: "Denmark", type: "country", parent: "europe" },
  { value: "EE", label: "Estonia", type: "country", parent: "europe" },
  { value: "FI", label: "Finland", type: "country", parent: "europe" },
  { value: "FR", label: "France", type: "country", parent: "europe" },
  { value: "DE", label: "Germany", type: "country", parent: "europe" },
  { value: "GR", label: "Greece", type: "country", parent: "europe" },
  { value: "HU", label: "Hungary", type: "country", parent: "europe" },
  { value: "IS", label: "Iceland", type: "country", parent: "europe" },
  { value: "IE", label: "Ireland", type: "country", parent: "europe" },
  { value: "IT", label: "Italy", type: "country", parent: "europe" },
  { value: "XK", label: "Kosovo", type: "country", parent: "europe" },
  { value: "LV", label: "Latvia", type: "country", parent: "europe" },
  { value: "LI", label: "Liechtenstein", type: "country", parent: "europe" },
  { value: "LT", label: "Lithuania", type: "country", parent: "europe" },
  { value: "LU", label: "Luxembourg", type: "country", parent: "europe" },
  { value: "MT", label: "Malta", type: "country", parent: "europe" },
  { value: "MD", label: "Moldova", type: "country", parent: "europe" },
  { value: "MC", label: "Monaco", type: "country", parent: "europe" },
  { value: "ME", label: "Montenegro", type: "country", parent: "europe" },
  { value: "NL", label: "Netherlands", type: "country", parent: "europe" },
  { value: "MK", label: "North Macedonia", type: "country", parent: "europe" },
  { value: "NO", label: "Norway", type: "country", parent: "europe" },
  { value: "PL", label: "Poland", type: "country", parent: "europe" },
  { value: "PT", label: "Portugal", type: "country", parent: "europe" },
  { value: "RO", label: "Romania", type: "country", parent: "europe" },
  { value: "RU", label: "Russia", type: "country", parent: "europe" },
  { value: "SM", label: "San Marino", type: "country", parent: "europe" },
  { value: "RS", label: "Serbia", type: "country", parent: "europe" },
  { value: "SK", label: "Slovakia", type: "country", parent: "europe" },
  { value: "SI", label: "Slovenia", type: "country", parent: "europe" },
  { value: "ES", label: "Spain", type: "country", parent: "europe" },
  { value: "SE", label: "Sweden", type: "country", parent: "europe" },
  { value: "CH", label: "Switzerland", type: "country", parent: "europe" },
  { value: "UA", label: "Ukraine", type: "country", parent: "europe" },
  { value: "GB", label: "United Kingdom", type: "country", parent: "europe" },
  // ── NORTH AMERICA ──
  { value: "AG", label: "Antigua and Barbuda", type: "country", parent: "north-america" },
  { value: "BS", label: "Bahamas", type: "country", parent: "north-america" },
  { value: "BB", label: "Barbados", type: "country", parent: "north-america" },
  { value: "BZ", label: "Belize", type: "country", parent: "north-america" },
  { value: "CA", label: "Canada", type: "country", parent: "north-america" },
  { value: "CR", label: "Costa Rica", type: "country", parent: "north-america" },
  { value: "CU", label: "Cuba", type: "country", parent: "north-america" },
  { value: "DM", label: "Dominica", type: "country", parent: "north-america" },
  { value: "DO", label: "Dominican Republic", type: "country", parent: "north-america" },
  { value: "SV", label: "El Salvador", type: "country", parent: "north-america" },
  { value: "GD", label: "Grenada", type: "country", parent: "north-america" },
  { value: "GT", label: "Guatemala", type: "country", parent: "north-america" },
  { value: "HT", label: "Haiti", type: "country", parent: "north-america" },
  { value: "HN", label: "Honduras", type: "country", parent: "north-america" },
  { value: "JM", label: "Jamaica", type: "country", parent: "north-america" },
  { value: "MX", label: "Mexico", type: "country", parent: "north-america" },
  { value: "NI", label: "Nicaragua", type: "country", parent: "north-america" },
  { value: "PA", label: "Panama", type: "country", parent: "north-america" },
  { value: "KN", label: "Saint Kitts and Nevis", type: "country", parent: "north-america" },
  { value: "LC", label: "Saint Lucia", type: "country", parent: "north-america" },
  { value: "VC", label: "Saint Vincent", type: "country", parent: "north-america" },
  { value: "TT", label: "Trinidad and Tobago", type: "country", parent: "north-america" },
  { value: "US", label: "United States", type: "country", parent: "north-america" },
  // ── SOUTH AMERICA ──
  { value: "AR", label: "Argentina", type: "country", parent: "south-america" },
  { value: "BO", label: "Bolivia", type: "country", parent: "south-america" },
  { value: "BR", label: "Brazil", type: "country", parent: "south-america" },
  { value: "CL", label: "Chile", type: "country", parent: "south-america" },
  { value: "CO", label: "Colombia", type: "country", parent: "south-america" },
  { value: "EC", label: "Ecuador", type: "country", parent: "south-america" },
  { value: "GY", label: "Guyana", type: "country", parent: "south-america" },
  { value: "PY", label: "Paraguay", type: "country", parent: "south-america" },
  { value: "PE", label: "Peru", type: "country", parent: "south-america" },
  { value: "SR", label: "Suriname", type: "country", parent: "south-america" },
  { value: "UY", label: "Uruguay", type: "country", parent: "south-america" },
  { value: "VE", label: "Venezuela", type: "country", parent: "south-america" },
  // ── MIDDLE EAST ──
  { value: "BH", label: "Bahrain", type: "country", parent: "middle-east" },
  { value: "IR", label: "Iran", type: "country", parent: "middle-east" },
  { value: "IQ", label: "Iraq", type: "country", parent: "middle-east" },
  { value: "IL", label: "Israel", type: "country", parent: "middle-east" },
  { value: "JO", label: "Jordan", type: "country", parent: "middle-east" },
  { value: "KW", label: "Kuwait", type: "country", parent: "middle-east" },
  { value: "LB", label: "Lebanon", type: "country", parent: "middle-east" },
  { value: "OM", label: "Oman", type: "country", parent: "middle-east" },
  { value: "PS", label: "Palestine", type: "country", parent: "middle-east" },
  { value: "QA", label: "Qatar", type: "country", parent: "middle-east" },
  { value: "SA", label: "Saudi Arabia", type: "country", parent: "middle-east" },
  { value: "SY", label: "Syria", type: "country", parent: "middle-east" },
  { value: "TR", label: "Turkey", type: "country", parent: "middle-east" },
  { value: "AE", label: "UAE", type: "country", parent: "middle-east" },
  { value: "YE", label: "Yemen", type: "country", parent: "middle-east" },
  // ── OCEANIA ──
  { value: "AU", label: "Australia", type: "country", parent: "oceania" },
  { value: "FJ", label: "Fiji", type: "country", parent: "oceania" },
  { value: "NZ", label: "New Zealand", type: "country", parent: "oceania" },
  { value: "PG", label: "Papua New Guinea", type: "country", parent: "oceania" },
  { value: "WS", label: "Samoa", type: "country", parent: "oceania" },
  { value: "TO", label: "Tonga", type: "country", parent: "oceania" },
  { value: "VU", label: "Vanuatu", type: "country", parent: "oceania" },
];

// ══════════════════════════════════════════════════
// SUB-REGIONS (States / Counties / Provinces)
// ══════════════════════════════════════════════════

// ── KENYA (all 47 counties) ──
const KENYA_COUNTIES: GeoOption[] = [
  { value: "KE-01", label: "Mombasa", type: "county", parent: "KE" },
  { value: "KE-02", label: "Kwale", type: "county", parent: "KE" },
  { value: "KE-03", label: "Kilifi", type: "county", parent: "KE" },
  { value: "KE-04", label: "Tana River", type: "county", parent: "KE" },
  { value: "KE-05", label: "Lamu", type: "county", parent: "KE" },
  { value: "KE-06", label: "Taita-Taveta", type: "county", parent: "KE" },
  { value: "KE-07", label: "Garissa", type: "county", parent: "KE" },
  { value: "KE-08", label: "Wajir", type: "county", parent: "KE" },
  { value: "KE-09", label: "Mandera", type: "county", parent: "KE" },
  { value: "KE-10", label: "Marsabit", type: "county", parent: "KE" },
  { value: "KE-11", label: "Isiolo", type: "county", parent: "KE" },
  { value: "KE-12", label: "Meru", type: "county", parent: "KE" },
  { value: "KE-13", label: "Tharaka-Nithi", type: "county", parent: "KE" },
  { value: "KE-14", label: "Embu", type: "county", parent: "KE" },
  { value: "KE-15", label: "Kitui", type: "county", parent: "KE" },
  { value: "KE-16", label: "Machakos", type: "county", parent: "KE" },
  { value: "KE-17", label: "Makueni", type: "county", parent: "KE" },
  { value: "KE-18", label: "Nyandarua", type: "county", parent: "KE" },
  { value: "KE-19", label: "Nyeri", type: "county", parent: "KE" },
  { value: "KE-20", label: "Kirinyaga", type: "county", parent: "KE" },
  { value: "KE-21", label: "Murang'a", type: "county", parent: "KE" },
  { value: "KE-22", label: "Kiambu", type: "county", parent: "KE" },
  { value: "KE-23", label: "Turkana", type: "county", parent: "KE" },
  { value: "KE-24", label: "West Pokot", type: "county", parent: "KE" },
  { value: "KE-25", label: "Samburu", type: "county", parent: "KE" },
  { value: "KE-26", label: "Trans-Nzoia", type: "county", parent: "KE" },
  { value: "KE-27", label: "Uasin Gishu", type: "county", parent: "KE" },
  { value: "KE-28", label: "Elgeyo-Marakwet", type: "county", parent: "KE" },
  { value: "KE-29", label: "Nandi", type: "county", parent: "KE" },
  { value: "KE-30", label: "Baringo", type: "county", parent: "KE" },
  { value: "KE-31", label: "Laikipia", type: "county", parent: "KE" },
  { value: "KE-32", label: "Nakuru", type: "county", parent: "KE" },
  { value: "KE-33", label: "Narok", type: "county", parent: "KE" },
  { value: "KE-34", label: "Kajiado", type: "county", parent: "KE" },
  { value: "KE-35", label: "Kericho", type: "county", parent: "KE" },
  { value: "KE-36", label: "Bomet", type: "county", parent: "KE" },
  { value: "KE-37", label: "Kakamega", type: "county", parent: "KE" },
  { value: "KE-38", label: "Vihiga", type: "county", parent: "KE" },
  { value: "KE-39", label: "Bungoma", type: "county", parent: "KE" },
  { value: "KE-40", label: "Busia", type: "county", parent: "KE" },
  { value: "KE-41", label: "Siaya", type: "county", parent: "KE" },
  { value: "KE-42", label: "Kisumu", type: "county", parent: "KE" },
  { value: "KE-43", label: "Homa Bay", type: "county", parent: "KE" },
  { value: "KE-44", label: "Migori", type: "county", parent: "KE" },
  { value: "KE-45", label: "Kisii", type: "county", parent: "KE" },
  { value: "KE-46", label: "Nyamira", type: "county", parent: "KE" },
  { value: "KE-47", label: "Nairobi", type: "county", parent: "KE" },
];

// ── NIGERIA (all 36 states + FCT) ──
const NIGERIA_STATES: GeoOption[] = [
  { value: "NG-AB", label: "Abia", type: "state", parent: "NG" },
  { value: "NG-AD", label: "Adamawa", type: "state", parent: "NG" },
  { value: "NG-AK", label: "Akwa Ibom", type: "state", parent: "NG" },
  { value: "NG-AN", label: "Anambra", type: "state", parent: "NG" },
  { value: "NG-BA", label: "Bauchi", type: "state", parent: "NG" },
  { value: "NG-BY", label: "Bayelsa", type: "state", parent: "NG" },
  { value: "NG-BE", label: "Benue", type: "state", parent: "NG" },
  { value: "NG-BO", label: "Borno", type: "state", parent: "NG" },
  { value: "NG-CR", label: "Cross River", type: "state", parent: "NG" },
  { value: "NG-DE", label: "Delta", type: "state", parent: "NG" },
  { value: "NG-EB", label: "Ebonyi", type: "state", parent: "NG" },
  { value: "NG-ED", label: "Edo", type: "state", parent: "NG" },
  { value: "NG-EK", label: "Ekiti", type: "state", parent: "NG" },
  { value: "NG-EN", label: "Enugu", type: "state", parent: "NG" },
  { value: "NG-FC", label: "FCT Abuja", type: "state", parent: "NG" },
  { value: "NG-GO", label: "Gombe", type: "state", parent: "NG" },
  { value: "NG-IM", label: "Imo", type: "state", parent: "NG" },
  { value: "NG-JI", label: "Jigawa", type: "state", parent: "NG" },
  { value: "NG-KD", label: "Kaduna", type: "state", parent: "NG" },
  { value: "NG-KN", label: "Kano", type: "state", parent: "NG" },
  { value: "NG-KT", label: "Katsina", type: "state", parent: "NG" },
  { value: "NG-KE", label: "Kebbi", type: "state", parent: "NG" },
  { value: "NG-KO", label: "Kogi", type: "state", parent: "NG" },
  { value: "NG-KW", label: "Kwara", type: "state", parent: "NG" },
  { value: "NG-LA", label: "Lagos", type: "state", parent: "NG" },
  { value: "NG-NA", label: "Nasarawa", type: "state", parent: "NG" },
  { value: "NG-NI", label: "Niger", type: "state", parent: "NG" },
  { value: "NG-OG", label: "Ogun", type: "state", parent: "NG" },
  { value: "NG-ON", label: "Ondo", type: "state", parent: "NG" },
  { value: "NG-OS", label: "Osun", type: "state", parent: "NG" },
  { value: "NG-OY", label: "Oyo", type: "state", parent: "NG" },
  { value: "NG-PL", label: "Plateau", type: "state", parent: "NG" },
  { value: "NG-RI", label: "Rivers", type: "state", parent: "NG" },
  { value: "NG-SO", label: "Sokoto", type: "state", parent: "NG" },
  { value: "NG-TA", label: "Taraba", type: "state", parent: "NG" },
  { value: "NG-YO", label: "Yobe", type: "state", parent: "NG" },
  { value: "NG-ZA", label: "Zamfara", type: "state", parent: "NG" },
];

// ── SOUTH AFRICA (9 provinces) ──
const SA_PROVINCES: GeoOption[] = [
  { value: "ZA-EC", label: "Eastern Cape", type: "province", parent: "ZA" },
  { value: "ZA-FS", label: "Free State", type: "province", parent: "ZA" },
  { value: "ZA-GP", label: "Gauteng", type: "province", parent: "ZA" },
  { value: "ZA-KZN", label: "KwaZulu-Natal", type: "province", parent: "ZA" },
  { value: "ZA-LP", label: "Limpopo", type: "province", parent: "ZA" },
  { value: "ZA-MP", label: "Mpumalanga", type: "province", parent: "ZA" },
  { value: "ZA-NC", label: "Northern Cape", type: "province", parent: "ZA" },
  { value: "ZA-NW", label: "North West", type: "province", parent: "ZA" },
  { value: "ZA-WC", label: "Western Cape", type: "province", parent: "ZA" },
];

// ── US (all 50 states + DC) ──
const US_STATES: GeoOption[] = [
  { value: "US-AL", label: "Alabama", type: "state", parent: "US" },
  { value: "US-AK", label: "Alaska", type: "state", parent: "US" },
  { value: "US-AZ", label: "Arizona", type: "state", parent: "US" },
  { value: "US-AR", label: "Arkansas", type: "state", parent: "US" },
  { value: "US-CA", label: "California", type: "state", parent: "US" },
  { value: "US-CO", label: "Colorado", type: "state", parent: "US" },
  { value: "US-CT", label: "Connecticut", type: "state", parent: "US" },
  { value: "US-DE", label: "Delaware", type: "state", parent: "US" },
  { value: "US-DC", label: "District of Columbia", type: "state", parent: "US" },
  { value: "US-FL", label: "Florida", type: "state", parent: "US" },
  { value: "US-GA", label: "Georgia", type: "state", parent: "US" },
  { value: "US-HI", label: "Hawaii", type: "state", parent: "US" },
  { value: "US-ID", label: "Idaho", type: "state", parent: "US" },
  { value: "US-IL", label: "Illinois", type: "state", parent: "US" },
  { value: "US-IN", label: "Indiana", type: "state", parent: "US" },
  { value: "US-IA", label: "Iowa", type: "state", parent: "US" },
  { value: "US-KS", label: "Kansas", type: "state", parent: "US" },
  { value: "US-KY", label: "Kentucky", type: "state", parent: "US" },
  { value: "US-LA", label: "Louisiana", type: "state", parent: "US" },
  { value: "US-ME", label: "Maine", type: "state", parent: "US" },
  { value: "US-MD", label: "Maryland", type: "state", parent: "US" },
  { value: "US-MA", label: "Massachusetts", type: "state", parent: "US" },
  { value: "US-MI", label: "Michigan", type: "state", parent: "US" },
  { value: "US-MN", label: "Minnesota", type: "state", parent: "US" },
  { value: "US-MS", label: "Mississippi", type: "state", parent: "US" },
  { value: "US-MO", label: "Missouri", type: "state", parent: "US" },
  { value: "US-MT", label: "Montana", type: "state", parent: "US" },
  { value: "US-NE", label: "Nebraska", type: "state", parent: "US" },
  { value: "US-NV", label: "Nevada", type: "state", parent: "US" },
  { value: "US-NH", label: "New Hampshire", type: "state", parent: "US" },
  { value: "US-NJ", label: "New Jersey", type: "state", parent: "US" },
  { value: "US-NM", label: "New Mexico", type: "state", parent: "US" },
  { value: "US-NY", label: "New York", type: "state", parent: "US" },
  { value: "US-NC", label: "North Carolina", type: "state", parent: "US" },
  { value: "US-ND", label: "North Dakota", type: "state", parent: "US" },
  { value: "US-OH", label: "Ohio", type: "state", parent: "US" },
  { value: "US-OK", label: "Oklahoma", type: "state", parent: "US" },
  { value: "US-OR", label: "Oregon", type: "state", parent: "US" },
  { value: "US-PA", label: "Pennsylvania", type: "state", parent: "US" },
  { value: "US-RI", label: "Rhode Island", type: "state", parent: "US" },
  { value: "US-SC", label: "South Carolina", type: "state", parent: "US" },
  { value: "US-SD", label: "South Dakota", type: "state", parent: "US" },
  { value: "US-TN", label: "Tennessee", type: "state", parent: "US" },
  { value: "US-TX", label: "Texas", type: "state", parent: "US" },
  { value: "US-UT", label: "Utah", type: "state", parent: "US" },
  { value: "US-VT", label: "Vermont", type: "state", parent: "US" },
  { value: "US-VA", label: "Virginia", type: "state", parent: "US" },
  { value: "US-WA", label: "Washington", type: "state", parent: "US" },
  { value: "US-WV", label: "West Virginia", type: "state", parent: "US" },
  { value: "US-WI", label: "Wisconsin", type: "state", parent: "US" },
  { value: "US-WY", label: "Wyoming", type: "state", parent: "US" },
];

// ── INDIA (all 28 states + 8 UTs) ──
const INDIA_STATES: GeoOption[] = [
  { value: "IN-AP", label: "Andhra Pradesh", type: "state", parent: "IN" },
  { value: "IN-AR", label: "Arunachal Pradesh", type: "state", parent: "IN" },
  { value: "IN-AS", label: "Assam", type: "state", parent: "IN" },
  { value: "IN-BR", label: "Bihar", type: "state", parent: "IN" },
  { value: "IN-CT", label: "Chhattisgarh", type: "state", parent: "IN" },
  { value: "IN-GA", label: "Goa", type: "state", parent: "IN" },
  { value: "IN-GJ", label: "Gujarat", type: "state", parent: "IN" },
  { value: "IN-HR", label: "Haryana", type: "state", parent: "IN" },
  { value: "IN-HP", label: "Himachal Pradesh", type: "state", parent: "IN" },
  { value: "IN-JH", label: "Jharkhand", type: "state", parent: "IN" },
  { value: "IN-KA", label: "Karnataka", type: "state", parent: "IN" },
  { value: "IN-KL", label: "Kerala", type: "state", parent: "IN" },
  { value: "IN-MP", label: "Madhya Pradesh", type: "state", parent: "IN" },
  { value: "IN-MH", label: "Maharashtra", type: "state", parent: "IN" },
  { value: "IN-MN", label: "Manipur", type: "state", parent: "IN" },
  { value: "IN-ML", label: "Meghalaya", type: "state", parent: "IN" },
  { value: "IN-MZ", label: "Mizoram", type: "state", parent: "IN" },
  { value: "IN-NL", label: "Nagaland", type: "state", parent: "IN" },
  { value: "IN-OD", label: "Odisha", type: "state", parent: "IN" },
  { value: "IN-PB", label: "Punjab", type: "state", parent: "IN" },
  { value: "IN-RJ", label: "Rajasthan", type: "state", parent: "IN" },
  { value: "IN-SK", label: "Sikkim", type: "state", parent: "IN" },
  { value: "IN-TN", label: "Tamil Nadu", type: "state", parent: "IN" },
  { value: "IN-TG", label: "Telangana", type: "state", parent: "IN" },
  { value: "IN-TR", label: "Tripura", type: "state", parent: "IN" },
  { value: "IN-UP", label: "Uttar Pradesh", type: "state", parent: "IN" },
  { value: "IN-UK", label: "Uttarakhand", type: "state", parent: "IN" },
  { value: "IN-WB", label: "West Bengal", type: "state", parent: "IN" },
  { value: "IN-DL", label: "Delhi", type: "state", parent: "IN" },
  { value: "IN-JK", label: "Jammu & Kashmir", type: "state", parent: "IN" },
];

// ── UK (regions/nations) ──
const UK_REGIONS: GeoOption[] = [
  { value: "GB-ENG", label: "England", type: "region", parent: "GB" },
  { value: "GB-SCT", label: "Scotland", type: "region", parent: "GB" },
  { value: "GB-WLS", label: "Wales", type: "region", parent: "GB" },
  { value: "GB-NIR", label: "Northern Ireland", type: "region", parent: "GB" },
  { value: "GB-LDN", label: "Greater London", type: "region", parent: "GB" },
  { value: "GB-NW", label: "North West England", type: "region", parent: "GB" },
  { value: "GB-WMD", label: "West Midlands", type: "region", parent: "GB" },
  { value: "GB-YH", label: "Yorkshire & Humber", type: "region", parent: "GB" },
  { value: "GB-SE", label: "South East England", type: "region", parent: "GB" },
  { value: "GB-SW", label: "South West England", type: "region", parent: "GB" },
  { value: "GB-EM", label: "East Midlands", type: "region", parent: "GB" },
  { value: "GB-NE", label: "North East England", type: "region", parent: "GB" },
];

// ── GERMANY (16 states) ──
const GERMANY_STATES: GeoOption[] = [
  { value: "DE-BW", label: "Baden-Württemberg", type: "state", parent: "DE" },
  { value: "DE-BY", label: "Bavaria", type: "state", parent: "DE" },
  { value: "DE-BE", label: "Berlin", type: "state", parent: "DE" },
  { value: "DE-BB", label: "Brandenburg", type: "state", parent: "DE" },
  { value: "DE-HB", label: "Bremen", type: "state", parent: "DE" },
  { value: "DE-HH", label: "Hamburg", type: "state", parent: "DE" },
  { value: "DE-HE", label: "Hesse", type: "state", parent: "DE" },
  { value: "DE-NI", label: "Lower Saxony", type: "state", parent: "DE" },
  { value: "DE-MV", label: "Mecklenburg-Vorpommern", type: "state", parent: "DE" },
  { value: "DE-NW", label: "North Rhine-Westphalia", type: "state", parent: "DE" },
  { value: "DE-RP", label: "Rhineland-Palatinate", type: "state", parent: "DE" },
  { value: "DE-SL", label: "Saarland", type: "state", parent: "DE" },
  { value: "DE-SN", label: "Saxony", type: "state", parent: "DE" },
  { value: "DE-ST", label: "Saxony-Anhalt", type: "state", parent: "DE" },
  { value: "DE-SH", label: "Schleswig-Holstein", type: "state", parent: "DE" },
  { value: "DE-TH", label: "Thuringia", type: "state", parent: "DE" },
];

// ── BRAZIL (27 states) ──
const BRAZIL_STATES: GeoOption[] = [
  { value: "BR-AC", label: "Acre", type: "state", parent: "BR" },
  { value: "BR-AL", label: "Alagoas", type: "state", parent: "BR" },
  { value: "BR-AP", label: "Amapá", type: "state", parent: "BR" },
  { value: "BR-AM", label: "Amazonas", type: "state", parent: "BR" },
  { value: "BR-BA", label: "Bahia", type: "state", parent: "BR" },
  { value: "BR-CE", label: "Ceará", type: "state", parent: "BR" },
  { value: "BR-DF", label: "Distrito Federal", type: "state", parent: "BR" },
  { value: "BR-ES", label: "Espírito Santo", type: "state", parent: "BR" },
  { value: "BR-GO", label: "Goiás", type: "state", parent: "BR" },
  { value: "BR-MA", label: "Maranhão", type: "state", parent: "BR" },
  { value: "BR-MT", label: "Mato Grosso", type: "state", parent: "BR" },
  { value: "BR-MS", label: "Mato Grosso do Sul", type: "state", parent: "BR" },
  { value: "BR-MG", label: "Minas Gerais", type: "state", parent: "BR" },
  { value: "BR-PA", label: "Pará", type: "state", parent: "BR" },
  { value: "BR-PB", label: "Paraíba", type: "state", parent: "BR" },
  { value: "BR-PR", label: "Paraná", type: "state", parent: "BR" },
  { value: "BR-PE", label: "Pernambuco", type: "state", parent: "BR" },
  { value: "BR-PI", label: "Piauí", type: "state", parent: "BR" },
  { value: "BR-RJ", label: "Rio de Janeiro", type: "state", parent: "BR" },
  { value: "BR-RN", label: "Rio Grande do Norte", type: "state", parent: "BR" },
  { value: "BR-RS", label: "Rio Grande do Sul", type: "state", parent: "BR" },
  { value: "BR-RO", label: "Rondônia", type: "state", parent: "BR" },
  { value: "BR-RR", label: "Roraima", type: "state", parent: "BR" },
  { value: "BR-SC", label: "Santa Catarina", type: "state", parent: "BR" },
  { value: "BR-SP", label: "São Paulo", type: "state", parent: "BR" },
  { value: "BR-SE", label: "Sergipe", type: "state", parent: "BR" },
  { value: "BR-TO", label: "Tocantins", type: "state", parent: "BR" },
];

// ── CHINA (provinces/regions) ──
const CHINA_PROVINCES: GeoOption[] = [
  { value: "CN-BJ", label: "Beijing", type: "province", parent: "CN" },
  { value: "CN-SH", label: "Shanghai", type: "province", parent: "CN" },
  { value: "CN-GD", label: "Guangdong", type: "province", parent: "CN" },
  { value: "CN-ZJ", label: "Zhejiang", type: "province", parent: "CN" },
  { value: "CN-JS", label: "Jiangsu", type: "province", parent: "CN" },
  { value: "CN-SD", label: "Shandong", type: "province", parent: "CN" },
  { value: "CN-HN", label: "Henan", type: "province", parent: "CN" },
  { value: "CN-SC", label: "Sichuan", type: "province", parent: "CN" },
  { value: "CN-HB", label: "Hubei", type: "province", parent: "CN" },
  { value: "CN-HuN", label: "Hunan", type: "province", parent: "CN" },
  { value: "CN-FJ", label: "Fujian", type: "province", parent: "CN" },
  { value: "CN-AH", label: "Anhui", type: "province", parent: "CN" },
  { value: "CN-LN", label: "Liaoning", type: "province", parent: "CN" },
  { value: "CN-JX", label: "Jiangxi", type: "province", parent: "CN" },
  { value: "CN-SX", label: "Shaanxi", type: "province", parent: "CN" },
  { value: "CN-GX", label: "Guangxi", type: "province", parent: "CN" },
  { value: "CN-YN", label: "Yunnan", type: "province", parent: "CN" },
  { value: "CN-TJ", label: "Tianjin", type: "province", parent: "CN" },
  { value: "CN-CQ", label: "Chongqing", type: "province", parent: "CN" },
  { value: "CN-HK", label: "Hong Kong", type: "province", parent: "CN" },
  { value: "CN-XZ", label: "Tibet", type: "province", parent: "CN" },
  { value: "CN-XJ", label: "Xinjiang", type: "province", parent: "CN" },
];

// ── CANADA (13 provinces/territories) ──
const CANADA_PROVINCES: GeoOption[] = [
  { value: "CA-AB", label: "Alberta", type: "province", parent: "CA" },
  { value: "CA-BC", label: "British Columbia", type: "province", parent: "CA" },
  { value: "CA-MB", label: "Manitoba", type: "province", parent: "CA" },
  { value: "CA-NB", label: "New Brunswick", type: "province", parent: "CA" },
  { value: "CA-NL", label: "Newfoundland", type: "province", parent: "CA" },
  { value: "CA-NS", label: "Nova Scotia", type: "province", parent: "CA" },
  { value: "CA-ON", label: "Ontario", type: "province", parent: "CA" },
  { value: "CA-PE", label: "Prince Edward Island", type: "province", parent: "CA" },
  { value: "CA-QC", label: "Quebec", type: "province", parent: "CA" },
  { value: "CA-SK", label: "Saskatchewan", type: "province", parent: "CA" },
  { value: "CA-NT", label: "Northwest Territories", type: "province", parent: "CA" },
  { value: "CA-NU", label: "Nunavut", type: "province", parent: "CA" },
  { value: "CA-YT", label: "Yukon", type: "province", parent: "CA" },
];

// ── AUSTRALIA (8 states/territories) ──
const AUSTRALIA_STATES: GeoOption[] = [
  { value: "AU-NSW", label: "New South Wales", type: "state", parent: "AU" },
  { value: "AU-VIC", label: "Victoria", type: "state", parent: "AU" },
  { value: "AU-QLD", label: "Queensland", type: "state", parent: "AU" },
  { value: "AU-WA", label: "Western Australia", type: "state", parent: "AU" },
  { value: "AU-SA", label: "South Australia", type: "state", parent: "AU" },
  { value: "AU-TAS", label: "Tasmania", type: "state", parent: "AU" },
  { value: "AU-ACT", label: "Australian Capital Territory", type: "state", parent: "AU" },
  { value: "AU-NT", label: "Northern Territory", type: "state", parent: "AU" },
];

// ── MEXICO (32 states) ──
const MEXICO_STATES: GeoOption[] = [
  { value: "MX-AGU", label: "Aguascalientes", type: "state", parent: "MX" },
  { value: "MX-BCN", label: "Baja California", type: "state", parent: "MX" },
  { value: "MX-BCS", label: "Baja California Sur", type: "state", parent: "MX" },
  { value: "MX-CAM", label: "Campeche", type: "state", parent: "MX" },
  { value: "MX-CHP", label: "Chiapas", type: "state", parent: "MX" },
  { value: "MX-CHH", label: "Chihuahua", type: "state", parent: "MX" },
  { value: "MX-CMX", label: "Ciudad de México", type: "state", parent: "MX" },
  { value: "MX-COA", label: "Coahuila", type: "state", parent: "MX" },
  { value: "MX-COL", label: "Colima", type: "state", parent: "MX" },
  { value: "MX-DUR", label: "Durango", type: "state", parent: "MX" },
  { value: "MX-GUA", label: "Guanajuato", type: "state", parent: "MX" },
  { value: "MX-GRO", label: "Guerrero", type: "state", parent: "MX" },
  { value: "MX-HID", label: "Hidalgo", type: "state", parent: "MX" },
  { value: "MX-JAL", label: "Jalisco", type: "state", parent: "MX" },
  { value: "MX-MEX", label: "México", type: "state", parent: "MX" },
  { value: "MX-MIC", label: "Michoacán", type: "state", parent: "MX" },
  { value: "MX-MOR", label: "Morelos", type: "state", parent: "MX" },
  { value: "MX-NAY", label: "Nayarit", type: "state", parent: "MX" },
  { value: "MX-NLE", label: "Nuevo León", type: "state", parent: "MX" },
  { value: "MX-OAX", label: "Oaxaca", type: "state", parent: "MX" },
  { value: "MX-PUE", label: "Puebla", type: "state", parent: "MX" },
  { value: "MX-QUE", label: "Querétaro", type: "state", parent: "MX" },
  { value: "MX-ROO", label: "Quintana Roo", type: "state", parent: "MX" },
  { value: "MX-SLP", label: "San Luis Potosí", type: "state", parent: "MX" },
  { value: "MX-SIN", label: "Sinaloa", type: "state", parent: "MX" },
  { value: "MX-SON", label: "Sonora", type: "state", parent: "MX" },
  { value: "MX-TAB", label: "Tabasco", type: "state", parent: "MX" },
  { value: "MX-TAM", label: "Tamaulipas", type: "state", parent: "MX" },
  { value: "MX-TLA", label: "Tlaxcala", type: "state", parent: "MX" },
  { value: "MX-VER", label: "Veracruz", type: "state", parent: "MX" },
  { value: "MX-YUC", label: "Yucatán", type: "state", parent: "MX" },
  { value: "MX-ZAC", label: "Zacatecas", type: "state", parent: "MX" },
];

// ── JAPAN (prefectures - key ones) ──
const JAPAN_PREFECTURES: GeoOption[] = [
  { value: "JP-TK", label: "Tokyo", type: "state", parent: "JP" },
  { value: "JP-OS", label: "Osaka", type: "state", parent: "JP" },
  { value: "JP-AI", label: "Aichi (Nagoya)", type: "state", parent: "JP" },
  { value: "JP-HK", label: "Hokkaido", type: "state", parent: "JP" },
  { value: "JP-FK", label: "Fukuoka", type: "state", parent: "JP" },
  { value: "JP-KG", label: "Kanagawa", type: "state", parent: "JP" },
  { value: "JP-KY", label: "Kyoto", type: "state", parent: "JP" },
  { value: "JP-HY", label: "Hyogo (Kobe)", type: "state", parent: "JP" },
  { value: "JP-ST", label: "Saitama", type: "state", parent: "JP" },
  { value: "JP-CB", label: "Chiba", type: "state", parent: "JP" },
  { value: "JP-HR", label: "Hiroshima", type: "state", parent: "JP" },
  { value: "JP-OK", label: "Okinawa", type: "state", parent: "JP" },
];

// ── FRANCE (regions) ──
const FRANCE_REGIONS: GeoOption[] = [
  { value: "FR-IDF", label: "Île-de-France (Paris)", type: "region", parent: "FR" },
  { value: "FR-ARA", label: "Auvergne-Rhône-Alpes", type: "region", parent: "FR" },
  { value: "FR-NAQ", label: "Nouvelle-Aquitaine", type: "region", parent: "FR" },
  { value: "FR-OCC", label: "Occitanie", type: "region", parent: "FR" },
  { value: "FR-HDF", label: "Hauts-de-France", type: "region", parent: "FR" },
  { value: "FR-GES", label: "Grand Est", type: "region", parent: "FR" },
  { value: "FR-PAC", label: "Provence-Alpes-Côte d'Azur", type: "region", parent: "FR" },
  { value: "FR-PDL", label: "Pays de la Loire", type: "region", parent: "FR" },
  { value: "FR-BRE", label: "Bretagne", type: "region", parent: "FR" },
  { value: "FR-NOR", label: "Normandie", type: "region", parent: "FR" },
  { value: "FR-BFC", label: "Bourgogne-Franche-Comté", type: "region", parent: "FR" },
  { value: "FR-CVL", label: "Centre-Val de Loire", type: "region", parent: "FR" },
  { value: "FR-COR", label: "Corse", type: "region", parent: "FR" },
];

// ── ETHIOPIA (regions) ──
const ETHIOPIA_REGIONS: GeoOption[] = [
  { value: "ET-AA", label: "Addis Ababa", type: "region", parent: "ET" },
  { value: "ET-AF", label: "Afar", type: "region", parent: "ET" },
  { value: "ET-AM", label: "Amhara", type: "region", parent: "ET" },
  { value: "ET-OR", label: "Oromia", type: "region", parent: "ET" },
  { value: "ET-SO", label: "Somali", type: "region", parent: "ET" },
  { value: "ET-TI", label: "Tigray", type: "region", parent: "ET" },
  { value: "ET-SN", label: "SNNPR", type: "region", parent: "ET" },
  { value: "ET-DD", label: "Dire Dawa", type: "region", parent: "ET" },
  { value: "ET-HA", label: "Harari", type: "region", parent: "ET" },
  { value: "ET-BE", label: "Benishangul-Gumuz", type: "region", parent: "ET" },
  { value: "ET-GA", label: "Gambela", type: "region", parent: "ET" },
  { value: "ET-SW", label: "South West Ethiopia", type: "region", parent: "ET" },
  { value: "ET-SI", label: "Sidama", type: "region", parent: "ET" },
];

// ── GHANA (regions) ──
const GHANA_REGIONS: GeoOption[] = [
  { value: "GH-AA", label: "Greater Accra", type: "region", parent: "GH" },
  { value: "GH-AH", label: "Ashanti", type: "region", parent: "GH" },
  { value: "GH-WP", label: "Western", type: "region", parent: "GH" },
  { value: "GH-EP", label: "Eastern", type: "region", parent: "GH" },
  { value: "GH-CP", label: "Central", type: "region", parent: "GH" },
  { value: "GH-NP", label: "Northern", type: "region", parent: "GH" },
  { value: "GH-VO", label: "Volta", type: "region", parent: "GH" },
  { value: "GH-BA", label: "Brong-Ahafo", type: "region", parent: "GH" },
  { value: "GH-UE", label: "Upper East", type: "region", parent: "GH" },
  { value: "GH-UW", label: "Upper West", type: "region", parent: "GH" },
];

// ── TANZANIA (regions - key ones) ──
const TANZANIA_REGIONS: GeoOption[] = [
  { value: "TZ-DS", label: "Dar es Salaam", type: "region", parent: "TZ" },
  { value: "TZ-DG", label: "Dodoma", type: "region", parent: "TZ" },
  { value: "TZ-AR", label: "Arusha", type: "region", parent: "TZ" },
  { value: "TZ-MW", label: "Mwanza", type: "region", parent: "TZ" },
  { value: "TZ-ZN", label: "Zanzibar", type: "region", parent: "TZ" },
  { value: "TZ-KL", label: "Kilimanjaro", type: "region", parent: "TZ" },
  { value: "TZ-MB", label: "Mbeya", type: "region", parent: "TZ" },
  { value: "TZ-MR", label: "Morogoro", type: "region", parent: "TZ" },
  { value: "TZ-TG", label: "Tanga", type: "region", parent: "TZ" },
  { value: "TZ-IR", label: "Iringa", type: "region", parent: "TZ" },
];

// ── EGYPT (governorates - key ones) ──
const EGYPT_GOVERNORATES: GeoOption[] = [
  { value: "EG-C", label: "Cairo", type: "province", parent: "EG" },
  { value: "EG-ALX", label: "Alexandria", type: "province", parent: "EG" },
  { value: "EG-GZ", label: "Giza", type: "province", parent: "EG" },
  { value: "EG-SHR", label: "Sharqia", type: "province", parent: "EG" },
  { value: "EG-DK", label: "Dakahlia", type: "province", parent: "EG" },
  { value: "EG-LX", label: "Luxor", type: "province", parent: "EG" },
  { value: "EG-ASN", label: "Aswan", type: "province", parent: "EG" },
  { value: "EG-SUZ", label: "Suez", type: "province", parent: "EG" },
  { value: "EG-IS", label: "Ismailia", type: "province", parent: "EG" },
  { value: "EG-PTS", label: "Port Said", type: "province", parent: "EG" },
];

// ── SAUDI ARABIA (regions) ──
const SAUDI_REGIONS: GeoOption[] = [
  { value: "SA-RY", label: "Riyadh", type: "region", parent: "SA" },
  { value: "SA-MK", label: "Makkah", type: "region", parent: "SA" },
  { value: "SA-MD", label: "Madinah", type: "region", parent: "SA" },
  { value: "SA-EP", label: "Eastern Province", type: "region", parent: "SA" },
  { value: "SA-AS", label: "Asir", type: "region", parent: "SA" },
  { value: "SA-TB", label: "Tabuk", type: "region", parent: "SA" },
  { value: "SA-HA", label: "Ha'il", type: "region", parent: "SA" },
  { value: "SA-JF", label: "Jazan", type: "region", parent: "SA" },
  { value: "SA-NJ", label: "Najran", type: "region", parent: "SA" },
  { value: "SA-QS", label: "Qassim", type: "region", parent: "SA" },
];

// ── UAE (emirates) ──
const UAE_EMIRATES: GeoOption[] = [
  { value: "AE-AZ", label: "Abu Dhabi", type: "state", parent: "AE" },
  { value: "AE-DU", label: "Dubai", type: "state", parent: "AE" },
  { value: "AE-SH", label: "Sharjah", type: "state", parent: "AE" },
  { value: "AE-AJ", label: "Ajman", type: "state", parent: "AE" },
  { value: "AE-FU", label: "Fujairah", type: "state", parent: "AE" },
  { value: "AE-RK", label: "Ras Al Khaimah", type: "state", parent: "AE" },
  { value: "AE-UQ", label: "Umm Al Quwain", type: "state", parent: "AE" },
];

// ── INDONESIA (provinces - key ones) ──
const INDONESIA_PROVINCES: GeoOption[] = [
  { value: "ID-JK", label: "Jakarta", type: "province", parent: "ID" },
  { value: "ID-JB", label: "West Java", type: "province", parent: "ID" },
  { value: "ID-JT", label: "Central Java", type: "province", parent: "ID" },
  { value: "ID-JI", label: "East Java", type: "province", parent: "ID" },
  { value: "ID-BA", label: "Bali", type: "province", parent: "ID" },
  { value: "ID-SU", label: "North Sumatra", type: "province", parent: "ID" },
  { value: "ID-SS", label: "South Sumatra", type: "province", parent: "ID" },
  { value: "ID-KS", label: "South Kalimantan", type: "province", parent: "ID" },
  { value: "ID-SA", label: "North Sulawesi", type: "province", parent: "ID" },
  { value: "ID-YO", label: "Yogyakarta", type: "province", parent: "ID" },
];

// ── Sub-region lookup ──
const SUB_REGION_MAP: Record<string, GeoOption[]> = {
  KE: KENYA_COUNTIES,
  NG: NIGERIA_STATES,
  ZA: SA_PROVINCES,
  US: US_STATES,
  IN: INDIA_STATES,
  GB: UK_REGIONS,
  DE: GERMANY_STATES,
  BR: BRAZIL_STATES,
  CN: CHINA_PROVINCES,
  CA: CANADA_PROVINCES,
  AU: AUSTRALIA_STATES,
  MX: MEXICO_STATES,
  JP: JAPAN_PREFECTURES,
  FR: FRANCE_REGIONS,
  ET: ETHIOPIA_REGIONS,
  GH: GHANA_REGIONS,
  TZ: TANZANIA_REGIONS,
  EG: EGYPT_GOVERNORATES,
  SA: SAUDI_REGIONS,
  AE: UAE_EMIRATES,
  ID: INDONESIA_PROVINCES,
};

export function getSubRegions(countryCode: string): GeoOption[] {
  return SUB_REGION_MAP[countryCode] || [];
}

export function getGeoLabel(selections: GeoOption[]): string {
  if (!selections.length) return "Global (All Markets)";
  if (selections.length === 1) return selections[0].label;
  if (selections.length <= 3) return selections.map(s => s.label).join(", ");
  return `${selections.length} regions selected`;
}

export function getGeoContextString(selections: GeoOption[]): string {
  if (!selections.length) return "global";
  return selections.map(s => s.label).join(", ");
}

/** Stable id for cache keys + snapshot scope (ISO-ish codes, sorted). */
export function getGeoScopeId(selections: GeoOption[]): string {
  if (!selections.length) return "global";
  return [...selections]
    .map(s => s.value)
    .sort((a, b) => a.localeCompare(b))
    .join("+");
}
