/**
 * Direct RSS URLs per country — complements Google News (which already aggregates many of these).
 * Expand over time; failed URLs are skipped at runtime. Prioritize national + business + tech.
 */
export const RSS_FEEDS_BY_COUNTRY: Record<string, string[]> = {
  KE: [
    "https://www.citizen.digital/feed/",
    "https://nation.africa/kenya/rss.xml",
    "https://www.standardmedia.co.ke/rss/",
    "https://www.standardmedia.co.ke/rss/business",
    "https://www.standardmedia.co.ke/rss/sports",
    "https://www.businessdailyafrica.com/rss",
    "https://www.the-star.co.ke/rss",
    "https://www.capitalfm.co.ke/news/feed/",
    "https://www.kenyans.co.ke/feed",
    "https://www.tuko.co.ke/feed",
    "https://www.pulselive.co.ke/feed",
    "https://www.kbc.co.ke/feed/",
    "https://www.k24tv.co.ke/feed/",
    "https://www.techweez.com/feed/",
    "https://www.kenyanwallstreet.co.ke/feed/",
    "https://www.mwakilishi.com/feed",
    "https://www.ghafla.co.ke/feed",
    "https://nairobiwire.com/feed",
    "https://www.medianmax.com/feed",
    "https://www.hapakenya.com/feed",
    "https://www.cio.co.ke/feed/",
    "https://www.sde.co.ke/feed/",
    "https://www.michezoafrika.com/feed",
    "https://www.peopledaily.ke/feed/",
    "https://www.metropol.co.ke/feed/",
    "https://www.knchr.org/feed",
    "https://www.afro.com/feed",
    "https://www.africa-newsroom.com/feed",
    "https://www.aa.com.tr/en/rss/default?cat=africa",
    "https://www.bbc.com/news/world/africa/rss.xml",
    "https://feeds.feedburner.com/coastweek",
    "https://www.knn.co.ke/feed",
    "https://www.radiomaisha.co.ke/feed/",
    "https://www.classic105.com/feed/",
    "https://www.kiss100.co.ke/feed/",
    "https://www.capitalfm.co.ke/sports/feed/",
    "https://www.ntsakele.co.za/feed",
    "https://www.kenyans.co.ke/sports/feed",
    "https://www.kenyans.co.ke/entertainment/feed",
    "https://feeds.bbci.co.uk/news/world/africa/rss.xml",
    "https://www.aljazeera.com/xml/rss/all.xml",
    "https://www.africanews.com/feed/rss",
    "https://www.reuters.com/rssFeed/worldNews",
    "https://www.reuters.com/rssFeed/businessNews",
    "https://www.ft.com/?format=rss",
    "https://feeds.a.dj.com/rss/RSSWorldNews",
    "https://rss.cnn.com/rss/edition_world.rss",
    "https://www.voanews.com/api/zq_ome$eq",
    "https://www.dw.com/en/rss-en_top-stories",
    "https://www.france24.com/en/rss",
    "https://www.theeastafrican.co.ke/rss.xml",
    "https://www.theeastafrican.co.ke/kenya/rss.xml",
    "https://www.businessdailyafrica.com/bd/rss.xml",
    "https://www.nation.africa/kenya/business/rss.xml",
    "https://www.nation.africa/kenya/news/rss.xml",
    "https://www.nation.africa/kenya/sports/rss.xml",
    "https://www.standardmedia.co.ke/rss/kenya",
    "https://www.standardmedia.co.ke/rss/world",
    "https://citizentv.co.ke/feed/",
    "https://www.k24tv.co.ke/feed",
  ],
  NG: [
    "https://punchng.com/feed/",
    "https://www.vanguardngr.com/feed/",
    "https://www.premiumtimesng.com/feed/",
    "https://www.nairametrics.com/feed/",
    "https://techcabal.com/feed/",
    "https://techpoint.africa/feed/",
    "https://www.thecable.ng/feed/",
    "https://guardian.ng/feed/",
    "https://www.channelstv.com/feed/",
    "https://dailypost.ng/feed/",
    "https://www.businessday.ng/feed/",
    "https://www.thisdaylive.com/feed/",
    "https://www.sunnewsonline.com/feed/",
    "https://www.independent.ng/feed/",
    "https://www.leadership.ng/feed/",
    "https://www.dailytrust.com.ng/feed/",
    "https://www.blueprint.ng/feed/",
    "https://www.tribuneonlineng.com/feed/",
    "https://www.nannews.ng/feed/",
  ],
  US: [
    "https://feeds.npr.org/1001/rss.xml",
    "https://rss.cnn.com/rss/edition.rss",
    "https://moxie.foxnews.com/google-publisher/latest.xml",
    "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best",
    "https://www.cbsnews.com/latest/rss/main",
    "https://abcnews.go.com/abcnews/topstories",
    "https://feeds.washingtonpost.com/rss/world",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml",
    "https://feeds.bloomberg.com/markets/news.rss",
    "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    "https://www.marketwatch.com/rss/topstories",
    "https://techcrunch.com/feed/",
    "https://www.theverge.com/rss/index.xml",
    "https://arstechnica.com/feed/",
    "https://www.wired.com/feed/rss",
  ],
  GB: [
    "https://feeds.bbci.co.uk/news/rss.xml",
    "https://www.theguardian.com/world/rss",
    "https://www.ft.com/?format=rss",
    "https://www.independent.co.uk/rss",
    "https://www.telegraph.co.uk/rss.xml",
  ],
  ZA: [
    "https://www.news24.com/RSS",
    "https://www.businesslive.co.za/rss/?section=South%20Africa",
    "https://www.dailymaverick.co.za/dmrss/",
    "https://www.iol.co.za/rss",
    "https://www.techcentral.co.za/feed/",
  ],
  IN: [
    "https://economictimes.indiatimes.com/rssfeedsdefault.cms",
    "https://www.livemint.com/rss/news",
    "https://www.moneycontrol.com/rss/latestnews.xml",
    "https://www.thehindu.com/news/national/?service=rss",
    "https://www.ndtv.com/rss",
    "https://inc42.com/feed/",
    "https://yourstory.com/feed/",
  ],
};

/** Domains for GDELT “site:” style doc pulls (batch OR queries). */
export const GDELT_DOMAIN_BATCHES: Record<string, string[][]> = {
  KE: [
    ["citizen.digital", "nation.africa", "standardmedia.co.ke", "businessdailyafrica.com", "the-star.co.ke"],
    ["capitalfm.co.ke", "kenyans.co.ke", "tuko.co.ke", "pulselive.co.ke", "kbc.co.ke"],
    ["techweez.com", "kenyanwallstreet.com", "cio.co.ke", "tv47.digital", "k24tv.co.ke"],
  ],
  NG: [
    ["punchng.com", "vanguardngr.com", "premiumtimesng.com", "nairametrics.com", "techcabal.com"],
    ["businessday.ng", "thecable.ng", "guardian.ng", "channelstv.com", "dailypost.ng"],
  ],
  US: [
    ["reuters.com", "bloomberg.com", "cnbc.com", "wsj.com", "nytimes.com"],
    ["techcrunch.com", "theverge.com", "marketwatch.com", "ft.com", "apnews.com"],
  ],
};
